image: node:18.16.0

cache: #  Parameter 'cache' to cache the installation files for your projects dependencies, for building faster
  paths:
    - node_modules/

stages:
  - prepare
  - test
  - build
  - deploy

prepare:
  stage: prepare
  script:
    - export NODE_ENV=development
    - npm ci
  only:
    - main # or dev, the branch you want to publish

build:
  stage: build
  script:
    - export NODE_ENV=production
    - npm run build

  artifacts:
    paths:
      - dist


test:
  stage: test
  script: npm run test

pages:
  # Another interesting concept to keep in mind are build stages. Your web app can pass through a lot of tests and other tasks until it’s deployed to staging or production environments. There are three default stages on GitLab CI: build, test, and deploy. To specify which stage your job is running, simply add another line to your CI:
  stage: deploy
  script:
    - ls dist
    - rm -rf public
    - mkdir public
    - cp -r dist/* public
    - ls public
  artifacts:
    paths:
      - public # mandatory, other folder won't work
