image: mcr.microsoft.com/playwright:v1.44.0-jammy

# cache: #  Parameter 'cache' to cache the installation files for your projects dependencies, for building faster
#   paths:
#     - graphgadget/

stages:
  - prepare
  - check
  - build
  - test
  - deploy

prepare:
  stage: prepare
  script:
    - cd graphgadget
    - npm ci
  artifacts:
   paths:
   - graphgadget/node_modules

check:
  stage: check
  script:
    - cd graphgadget
    - npm run lint

build:
  stage: build
  script:
    - cd graphgadget
    - npm run build
  artifacts:
   paths: 
     - graphgadget/build # used for deploying
     - graphgadget/.svelte-kit/tsconfig.json # used by testing

test-unit:
  stage: test
  script: 
    - cd graphgadget
    - npm run test:unit
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: graphgadget/coverage/cobertura-coverage.xml
  coverage: '/^Statements\s*:\s*([^%]+)/'

test-system:
  stage: test
  script: 
    - cd graphgadget
    - npm run test:integration

pages:
  stage: deploy
  script:
  - mkdir .public
  - cp -r graphgadget/build/* .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
    - dev
