image: mcr.microsoft.com/playwright:v1.44.0-jammy

# cache: #  Parameter 'cache' to cache the installation files for your projects dependencies, for building faster
#   paths:
#     - metaspeech/

stages:
  - prepare
  - check
  - build
  - test
  - deploy

prepare:
  stage: prepare
  script:
    - cd metaspeech
    - npm ci
  artifacts:
   paths:
   - metaspeech/node_modules
   expire_in: 1 hour

check:
  stage: check
  script:
    - cd metaspeech
    - npm run lint

build:
  stage: build
  script:
    - cd metaspeech
    - npm run build
  artifacts:
   paths: 
     - metaspeech/build # used for deploying
     - metaspeech/.svelte-kit/tsconfig.json # used by testing
   expire_in: 1 hour

test-unit:
  stage: test
  script: 
    - cd metaspeech
    - npm run test:unit
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: metaspeech/coverage/cobertura-coverage.xml
  coverage: '/^Statements\s*:\s*([^%]+)/'

test-system:
  stage: test
  script: 
    - cd metaspeech
    - npm run test:integration

pages:
  stage: deploy
  script:
  - mkdir .public
  - cp -r metaspeech/build/* .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
    - dev
